### ISSUE TITLE
Outdated Version

### ISSUE THREAD

**Issue by ebarranco** [flathub/fr.natron.Natron#10]
Currently both versions, installer and portable stopped working for me in Linux, so  I'm using flatpak it works but I have the 2.3.13 version installed now. The information like 'Updated'  and 'Version' are blank in flathub.

**Comment by Sunderland93** [comment]
There are various issues to build Natron 2.3.14 and plugins with updated SDK 18.08. I work on resolve this issues.

**Comment by ebarranco** [comment]
thanks.
