### ISSUE TITLE
Updated version does not work.  

### ISSUE THREAD

**Issue by ebarranco** [flathub/fr.natron.Natron#12]
Hi I updated Natron today and now it has the same problem that the official installer and portable and don't start the program.
```

Load OFX Plugins: scan plugins... 
couldn't open library /app/Plugins/OFX/Natron/Arena.ofx.bundle/Contents/Linux-x86-64/Arena.ofx because /usr/lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end
Caught segmentation fault (SIGSEGV) from thread Main(0x55ff6829e610), faulty address is 0x42c00 from 0x42c0
```

**Comment by Sunderland93** [comment]
Hmm. I'm not sure, but maybe that's because Natron build with bundled cairo, and with librsvg from Flatpak SDK...

**Comment by Sunderland93** [comment]
@ebarranco can you please testing new build?
`flatpak install --user https://dl.flathub.org/build-repo/509/fr.natron.Natron.flatpakref`

**Comment by ebarranco** [comment]
@Sunderland93 Hi! Natron starts now. Everything seems to be in place and working.
