### ISSUE TITLE
video read does not work

### ISSUE THREAD

**Issue by sonigfr** [flathub/fr.natron.Natron#14]
It seems on Natron 2.3.14 I can't read any video files with the error : 
'read1 error: Invalid data found when processing input'

In any format, I tried uncompressed .mov, h264/mp4, dv, nothing works. 

I tried portable 2.3.14 version from Natron site, all format works flawlessly, so I suppose it comes from the flatpak version.

**Comment by Sunderland93** [comment]
@sonigfr can you please test with latest update?

**Comment by lsde** [comment]
doesn't work.

**Comment by sonigfr** [comment]
@Sunderland93 I am on Debian 10 Buster, I installed Flatpak, Gnome Software Flatpak plugin, Added the Flathub repository on my system, flathub package normally update automatically from Debian Gnome Software so all seems to be updated and as on this page https://flathub.org/apps/details/fr.natron.Natron , 2.3.14 already seems to be the latest update. Is there any difference ?

**Comment by Gaspared** [comment]
doesn't work in my flatpak version 2.3.14.

**Comment by Sunderland93** [comment]
Should be fixed in #19
