### ISSUE TITLE
video write does not work

### ISSUE THREAD

**Issue by Yarsqrt-1** [flathub/fr.natron.Natron#15]
It seams that the video write does not work for version 2.3.14. When I try to create a write node for a mp4 file, I get the error:

"Error while creating node fr.inria.openfx.WriteFFmpeg: Write1 error: writer was configured for unavailable codec." 

It looks exactly like the closed issue here: https://github.com/MrKepzie/Natron/issues/1774

When using the portable 2.3.14 version from Natron site, it does work, so I suppose it comes from the flatpak version.

**Comment by Sunderland93** [comment]
@Yarsqrt-1 Can you please test with latest update?

**Comment by doradoro** [comment]
Still missing.

**Comment by lsde** [comment]
writing doesn't work.

**Comment by doradoro** [comment]
i switched to flowblade

**Comment by rodlie** [comment]
Natron is not dead and is still maintained.

Shouldn't this issue be rather easy to fix? It's running in a sandbox? Then there must be a setting/config to allow the app to access various parts of the file system (like your home dir etc)?

**Comment by rodlie** [comment]
* http://docs.flatpak.org/en/latest/manifests.html#finishing
 * http://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access
 * http://docs.flatpak.org/en/latest/sandbox-permissions.html#standard-permissions

**Comment by Sunderland93** [comment]
Should be fixed in #19
