### ISSUE TITLE
Community plugins install

### ISSUE THREAD

**Issue by matteocrippa** [flathub/fr.natron.Natron#26]
I see that the basic installation via flathub has no community plugins, how can I add them?

Was considering if not worth add them directly in the flathub? 

https://github.com/NatronGitHub/natron-plugins

**Comment by rodlie** [comment]
Instructions on how to add them are on the page your are linking to. Just download the folder somewhere and add it to Natron.

``Edit>Preferences>Plugins>pyplug search path>add>the extracted file location``

We don't include the community plugins in the official releases, so the flatpak shouldn't do that either (IMHO).

**Comment by matteocrippa** [comment]
@rodlie thx
