### ISSUE TITLE
Natron not up to date

### ISSUE THREAD

**Issue by Chantology** [flathub/fr.natron.Natron#36]
Who is maintaining the Flatpak version of Natron? There is already Natron 2.5.0 released on Github, but only 2.4.4 on Flathub:
https://flathub.org/apps/fr.natron.Natron

Natron Github: 
https://github.com/NatronGitHub/Natron

**Comment by rodlie** [comment]
I don't know if we have a maintainer anymore(?). If @Sunderland93 don't want to maintain it anymore I can probably bump the version(?).

Also note that the flatpak is just a repack of the official binaries.

**Comment by Sunderland93** [comment]
Hi, sorry for the delay. I'll update package soon

**Comment by rodlie** [comment]
No problem  :+1: (no rush)
