### ISSUE TITLE
runtime  is end-of-life

### ISSUE THREAD

**Issue by khaled-nedjar** [flathub/fr.natron.Natron#38]
Info: runtime org.freedesktop.Sdk branch 22.08 is end-of-life, with reason:
   org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   fr.natron.Natron

Info: runtime org.freedesktop.Platform.GL.default branch 22.08-extra is end-of-life, with reason:
   org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   fr.natron.Natron

Info: runtime org.freedesktop.Platform.GL.default branch 22.08 is end-of-life, with reason:
   org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   fr.natron.Natron

**Comment by kjcole** [comment]
Actually there are four such errors on my system. Summarizing:

### end-of-life runtimes no longer receiving fixes and security updates:
* `org.freedesktop.Sdk` branch **22.08**
* `org.freedesktop.Platform.VAAPI.Intel` branch **22.08**
* `org.freedesktop.Platform.GL.default` branch **22.08**
* `org.freedesktop.Platform.GL.default` branch **22.08-extra**

**Comment by erentar** [comment]
```
Info: runtime org.freedesktop.Sdk branch 22.08 is end-of-life, with reason:
   org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   fr.natron.Natron

Info: runtime org.freedesktop.Platform.GL.default branch 22.08-extra is end-of-life, with reason:
   org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   fr.natron.Natron

Info: runtime org.freedesktop.Platform.GL.default branch 22.08 is end-of-life, with reason:
   org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   fr.natron.Natron
```

**Comment by rodlie** [comment]
@Sunderland93 maintains the flatpak for us, I don't know if he still is active.

This is just a repack so just bumping the sdk's should be enough(?, I don't use the flatpak).
