### ISSUE TITLE
upgrade to 2.3.13

### ISSUE THREAD

**Issue by devernay** [flathub/fr.natron.Natron#5]
Natron 2.3.13 release notes:

- Fix default value for file premult in ReadSVG (should be premultiplied).
- HSV values in the viewer info lines are now computed from linear RGB #286.
- RGBToHSV, HSVToRGB, RGBToHSL, HSLToRGB, RGBToHSI, HSIToRGB: Use linear RGB values in computation #286.
- Tracker: fix bug where Transform tracking was wrong when using more than 1 point #289.

Also:
- GMIC/CImg upgraded to 2.3.1
- lodepng in openfx-arena upgraded
- dependencies were updated (ffmpeg 4.0.1, etc, see https://github.com/NatronGitHub/Natron/blob/RB-2.3/tools/jenkins/include/scripts/build-Linux-sdk.sh )

**Comment by Sunderland93** [comment]
I'll upgrade Natron tomorrow
