### ISSUE TITLE
prepare 2.3.14 release

### ISSUE THREAD

**Issue by devernay** [flathub/fr.natron.Natron#7]
not many changes, but probably my final release. you can see changes in https://github.com/NatronGitHub/Natron/compare/f57a7b0629e5048989660f3fef63c278d4922ca6...2.3.14

the dependencies that changed are:

- CURL_VERSION=7.61.0
- HARFBUZZ_VERSION=1.8.2
- MAGICK_VERSION=6.9.10-5 (or any newer 6.9.10 version)

**Comment by Sunderland93** [comment]
>  probably my final release

What do you mean?

**Comment by devernay** [comment]
I mean I am not able to maintain Natron anymore

**Comment by Sunderland93** [comment]
> I mean I am not able to maintain Natron anymore

Sad to hear that. I'll prepare update for Natron soon

**Comment by devernay** [comment]
I'm fixing a last issue in the gmic plugins, it should be ready for WednesdayLe 22 juil. 2018 19:04, Aleksey Samoilov <notifications@github.com> a écrit :
I mean I am not able to maintain Natron anymore

Sad to hear that. I'll prepare update for Natron soon
